// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524214454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.SuperLottoPrizes", b =>
                {
                    b.Property<int>("DrawNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrawNumber"));

                    b.Property<long>("FiveMatchesPlusMegaPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("FiveMatchesPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("FourMatchesPlusMegaPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("FourMatchesPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("MegaMatchOnlyPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("OneMatchPlusMegaPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("ThreeMatchesPlusMegaPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("ThreeMatchesPrizeAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("TwoMatchesPlusMegaPrizeAmount")
                        .HasColumnType("bigint");

                    b.HasKey("DrawNumber");

                    b.ToTable("SuperLottoPrizes", "LottoChecker");

                    b.HasData(
                        new
                        {
                            DrawNumber = 1001,
                            FiveMatchesPlusMegaPrizeAmount = 50000000L,
                            FiveMatchesPrizeAmount = 1000000L,
                            FourMatchesPlusMegaPrizeAmount = 50000L,
                            FourMatchesPrizeAmount = 1000L,
                            MegaMatchOnlyPrizeAmount = 2L,
                            OneMatchPlusMegaPrizeAmount = 5L,
                            ThreeMatchesPlusMegaPrizeAmount = 100L,
                            ThreeMatchesPrizeAmount = 20L,
                            TwoMatchesPlusMegaPrizeAmount = 10L
                        },
                        new
                        {
                            DrawNumber = 1002,
                            FiveMatchesPlusMegaPrizeAmount = 60000000L,
                            FiveMatchesPrizeAmount = 1100000L,
                            FourMatchesPlusMegaPrizeAmount = 60000L,
                            FourMatchesPrizeAmount = 1500L,
                            MegaMatchOnlyPrizeAmount = 3L,
                            OneMatchPlusMegaPrizeAmount = 6L,
                            ThreeMatchesPlusMegaPrizeAmount = 120L,
                            ThreeMatchesPrizeAmount = 25L,
                            TwoMatchesPlusMegaPrizeAmount = 12L
                        });
                });

            modelBuilder.Entity("API.Models.SuperLottoUserPicks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FifthPick")
                        .HasColumnType("int");

                    b.Property<int>("FirstPick")
                        .HasColumnType("int");

                    b.Property<int>("FourthPick")
                        .HasColumnType("int");

                    b.Property<int>("MegaPick")
                        .HasColumnType("int");

                    b.Property<int>("RowCheckSum")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<int>("SecondPick")
                        .HasColumnType("int");

                    b.Property<int>("ThirdPick")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("SuperLottoUserPicks", "LottoChecker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            FifthPick = 46,
                            FirstPick = 5,
                            FourthPick = 34,
                            MegaPick = 10,
                            RowCheckSum = 0,
                            SecondPick = 12,
                            ThirdPick = 23,
                            UserId = "user1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            FifthPick = 45,
                            FirstPick = 3,
                            FourthPick = 38,
                            MegaPick = 7,
                            RowCheckSum = 0,
                            SecondPick = 19,
                            ThirdPick = 27,
                            UserId = "user2"
                        });
                });

            modelBuilder.Entity("API.Models.SuperLottoWinningNumbers", b =>
                {
                    b.Property<int>("DrawNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrawNumber"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MegaNumber")
                        .HasColumnType("int");

                    b.Property<int>("Number1")
                        .HasColumnType("int");

                    b.Property<int>("Number2")
                        .HasColumnType("int");

                    b.Property<int>("Number3")
                        .HasColumnType("int");

                    b.Property<int>("Number4")
                        .HasColumnType("int");

                    b.Property<int>("Number5")
                        .HasColumnType("int");

                    b.HasKey("DrawNumber");

                    b.ToTable("SuperLottoWinningNumbers", "LottoChecker");

                    b.HasData(
                        new
                        {
                            DrawNumber = 1001,
                            DrawDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MegaNumber = 10,
                            Number1 = 5,
                            Number2 = 12,
                            Number3 = 23,
                            Number4 = 34,
                            Number5 = 46
                        },
                        new
                        {
                            DrawNumber = 1002,
                            DrawDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MegaNumber = 7,
                            Number1 = 3,
                            Number2 = 19,
                            Number3 = 27,
                            Number4 = 38,
                            Number5 = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
